### ISSUE TITLE
Encode alias description in sender name instead

### ISSUE THREAD

**Issue by mcg88** [fterh/heimdall#16]
cool project. I built something very similar in Python using Lambda & SES to manage my personal email. I like what you did with replies as I hadn't thought of going that far. 

One question, when sending the reply, do you remove the prepended subject info before shipping it back to the original sender? Threads could get quite messy if it keeps prepending subjects on each reply. Also, when replying does the lambda cc the email to the original cc list? So the receiver should REPLY vs Reply ALL when responding? 

Another suggestion that I think adds some flexibility would be a configuration that would allow all aliases by default and potentially have a way of disabling them. So if I was signing up for medium i could just use medium@myemaildomain.com without having to take the extra set of enabling that alias. 

Anyway, wish it was Python so I could contribute, but really like what you have done.

**Comment by fterh** [comment]
Hi! Thanks for your questions.

1. No, I don't process the email subject at all.

2. Nope, CC-list is cleared out when replying (i.e. forwarding emails sent from personal email to original sender). See: https://github.com/fterh/heimdall/blob/eb058e17735d38bc126412c4ad2136b261fa7b64/lib/forwardOutbound.ts#L79-L88 (no CC property).

3. That was raised by someone in my hackernews submission's comments. I think it's definitely a possible use case, but I personally prefer a blacklist by default vs whitelist by default workflow. (Also, whitelist by default is susceptible to abuse - e.g. I could start spamming random email addresses to overwhelm your inbox and you can't block them).

**Comment by mcg88** [comment]
To further address #1:

If I receive an email on the "adghkjshdhg" alias with teh subject "Check out our new features", I will receive that in my inbox with "[adghkjshdhg] Check out our new features", and I reply to it. The original sender will see the modified subject? I could imagine this might break some helpdesk integrations.

**Comment by fterh** [comment]
Technically you wouldn't receive "[adghkjshdhg] Check out our new features", but rather "[Alias description] Check out our new features", where "Alias description" is what you associated the alias with (e.g. Service X).

I imagine there must be a better way to include alias description, maybe by encoding it in the sender name instead. That's a good point, thanks for your suggestion1

**Comment by fterh** [comment]
Closing this. Decided to merge into #23 instead.
