### ISSUE TITLE
yarn global add serverless . fails

### ISSUE THREAD

**Issue by derekslenk** [fterh/heimdall#35]
Something is wrong with the serveless install - it keeps failing:

➜  heimdall git:(master) yarn global add serverless .
yarn global v1.21.1
[1/4] Resolving packages...
error Received malformed response from registry for ".". The registry may be down.
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.

Here is a verbose log: https://pastebin.com/k2e6jZsy

Details:
➜  ~ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"
➜  ~ node --version
v12.16.1
➜  ~ yarn --version
1.21.1

**Comment by fterh** [comment]
This is an issue with yarn/your yarn config, not this project. Maybe try re-installing yarn or posting on the yarn issues page?

**Comment by derekslenk** [comment]
I followed the default install instructions for nodejs 12.x from nodesource, and then just apt install yarn. Is there another prereq?

**Comment by fterh** [comment]
I'm not too sure, sorry. I installed node using nvm and yarn using homebrew on my Mac. Have you managed to resolve it?
