### ISSUE TITLE
Template error?

### ISSUE THREAD

**Issue by mcg88** [fterh/heimdall#40]
Running into the following issue when trying to deploy
```
Serverless: Validating template...
Serverless: [AWS cloudformation 400 0.67s 0 retries] validateTemplate({ TemplateURL:
   'xxxx/compiled-cloudformation-template.json' })

  Error --------------------------------------------------

  Error: The CloudFormation template is invalid: Template format error: Unresolved resource dependencies [S3BucketHeimdallprodmcg-heimdallx] in the Resources block of the template
```

The section I believe it is referencing is:
cloudformation-template-update-stack.json

```
              "Resource": {
                "Fn::Join": [
                  "",
                  [
                    "arn:aws:s3:::",
                    {
                      "Ref": "S3BucketHeimdallprodmcg-heimdallx"
                    },
                    "/*"
                  ]
                ]
              }
```

**Comment by fterh** [comment]
I'm not too familiar with serverless deployment, this is the first time I'm playing around with it :/ 

If you do manage to figure it out, please let me know if there's anything wrong/missing with my setup instructions!

**Comment by taylorhakes** [comment]
@mcg88 I am running into this as well. Were you able to figure it out?

**Comment by mcg88** [comment]
> @mcg88 I am running into this as well. Were you able to figure it out?

I don't recall exactly but I think it was related to aws regions
