### ISSUE TITLE
Attachments

### ISSUE THREAD

**Issue by MatissJanis** [fterh/heimdall#8]
What are your plans for adding attachments?

I've been using [this] for the last couple of years. The only big problem there is it drops all emails above 10mb (attachment issue).

[this]: https://github.com/arithmetric/aws-lambda-ses-forwarder

**Comment by fterh** [comment]
https://docs.aws.amazon.com/ses/latest/DeveloperGuide/quotas.html

It seems that there is a non-negotiable 10mb limit for sending and 30mb limit for receiving. I think that might be adequate for the vast majority of use cases, but to answer your question, I'll explore storing the attachment in a separate S3 bucket and linking to it from within the email (should it exceed AWS's size limits).
